# Generated by Django 5.2.7 on 2025-10-31 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Archivo')),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('enrolled', 'Inscritos'), ('private', 'Privado')], default='enrolled', max_length=20, verbose_name='Visibilidad')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido en')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de archivo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='Curso')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
