# Generated by Django 5.2.7 on 2026-01-13 02:13

import django.db.models.deletion
import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Enlace'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('file', 'Archivo'), ('link', 'Enlace')], default='file', max_length=10, verbose_name='Tipo de Material'),
        ),
        migrations.AddField(
            model_name='material',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre Original del Archivo'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='units.unit', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=materials.models.material_upload_path, verbose_name='Archivo'),
        ),
    ]
