# Generated by Django 5.2.10 on 2026-01-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_remove_unit'),
        ('materials', '0004_set_existing_materials_published'),
    ]

    operations = [
    ]
