# Generated by Django 5.2.10 on 2026-04-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_material_assignment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='mat_assign_pub_idx',
        ),
    ]
