# Generated by Django 5.2.10 on 2026-04-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_tema_remove_unique_order_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, help_text='Si se establece, el tema se publicará automáticamente en esta fecha y hora', null=True, verbose_name='Publicar el'),
        ),
    ]
