# Generated by Django 5.2.10 on 2026-04-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_exam_score_decimal_and_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='correct_explanation',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se muestra al alumno al revisar el examen.', verbose_name='Aclaración de la respuesta correcta (opcional)'),
        ),
    ]
