# Generated by Django 5.2.10 on 2026-05-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_themeexam_attendance_date_examattemptanswer_dont_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='focus_violation_log',
            field=models.JSONField(blank=True, default=list, verbose_name='Log de salidas de pantalla'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='focus_violations',
            field=models.PositiveIntegerField(default=0, verbose_name='Salidas de pantalla detectadas'),
        ),
        migrations.AddField(
            model_name='themeexam',
            name='max_focus_violations',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cantidad de veces que el alumno puede salir de la pantalla del examen antes de que se envíe automáticamente. 0 = sin límite.', verbose_name='Límite de salidas de pantalla'),
        ),
    ]
