# Generated by Django 5.2.10 on 2026-01-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_storage_gb', models.PositiveIntegerField(default=20, help_text='Espacio total contratado en el bucket (en GB)', verbose_name='Espacio Total (GB)')),
                ('alert_threshold_percent', models.PositiveIntegerField(default=80, help_text='Porcentaje de uso que activa una alerta (0-100)', verbose_name='Umbral de Alerta (%)')),
                ('alert_email', models.EmailField(blank=True, help_text='Email donde se enviarán las alertas de almacenamiento. Si está vacío, se usará el email del superusuario.', max_length=254, null=True, verbose_name='Email para Alertas')),
                ('alert_enabled', models.BooleanField(default=True, help_text='Activar o desactivar las notificaciones de almacenamiento', verbose_name='Alertas Habilitadas')),
                ('last_alert_sent', models.DateTimeField(blank=True, help_text='Fecha y hora de la última alerta enviada', null=True, verbose_name='Última Alerta Enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Configuración de Almacenamiento',
                'verbose_name_plural': 'Configuración de Almacenamiento',
                'ordering': ['-updated_at'],
            },
        ),
    ]
