# Generated by Django 5.2.7 on 2026-01-13 15:37

import assignments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_collaborators_course_is_paused'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('due_date', models.DateTimeField(verbose_name='Fecha Límite de Entrega')),
                ('final_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Final (No se pueden subir más archivos después de esta fecha)')),
                ('allow_group_work', models.BooleanField(default=False, verbose_name='Permitir Trabajo en Grupo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='Curso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='units.unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('file', models.FileField(upload_to=assignments.models.assignment_submission_upload_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nombre Original del Archivo')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Entregado en')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Entregado'), ('returned', 'Devuelto'), ('resubmitted', 'Reentregado')], default='submitted', max_length=20, verbose_name='Estado')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Devolución del Docente')),
                ('needs_resubmission', models.BooleanField(default=False, verbose_name='Requiere Reentrega')),
                ('feedback_given_at', models.DateTimeField(blank=True, null=True, verbose_name='Devolución dada en')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Tarea')),
                ('feedback_given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Devolución dada por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Entrega de Tarea',
                'verbose_name_plural': 'Entregas de Tareas',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Agregado en')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante Colaborador')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='assignments.assignmentsubmission', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Colaborador de Entrega',
                'verbose_name_plural': 'Colaboradores de Entregas',
                'ordering': ['added_at'],
                'unique_together': {('submission', 'student')},
            },
        ),
    ]
