# Generated by Django 5.2.10 on 2026-01-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_remove_unit'),
        ('assignments', '0004_set_existing_assignments_published'),
    ]

    operations = [
    ]
