# Generated by Django 5.2.10 on 2026-04-20 01:02

import assignments.models
import django.db.models.deletion
from django.db import migrations, models


def migrate_submission_files_to_attachments(apps, schema_editor):
    AssignmentSubmission = apps.get_model('assignments', 'AssignmentSubmission')
    AssignmentSubmissionFile = apps.get_model('assignments', 'AssignmentSubmissionFile')
    for sub in AssignmentSubmission.objects.exclude(file='').exclude(file__isnull=True):
        first_name = sub.original_filename or ''
        AssignmentSubmissionFile.objects.create(
            submission_id=sub.pk,
            file=sub.file,
            original_filename=first_name,
            order=0,
        )
        AssignmentSubmission.objects.filter(pk=sub.pk).update(file=None, original_filename=first_name)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_merge_20260127_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, help_text='Obsoleto: usar attachment_files. Se mantiene por compatibilidad.', null=True, upload_to=assignments.models.assignment_submission_upload_path, verbose_name='Archivo'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assignments.models.submission_attachment_upload_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='assignments.assignmentsubmission', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Archivo de entrega',
                'verbose_name_plural': 'Archivos de entrega',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(migrate_submission_files_to_attachments, noop_reverse),
    ]
