# Generated by Django 5.2.7 on 2026-01-13 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='courses_collaborated', to=settings.AUTH_USER_MODEL, verbose_name='Docentes Colaboradores'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='En Pausa'),
        ),
    ]
