# Generated by Django 5.2.7 on 2025-10-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor'), ('admin', 'Administrador')], default='student', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
